/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diseño;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ptoyecto.Peliculas;
import ptoyecto.Tipo_A;
import ptoyecto.Tipo_AA;
import ptoyecto.Tipo_B;
import ptoyecto.Tipo_B15;
import ptoyecto.Tipo_C;

/**
 *
 * @author Julio
 */
public class AgregarPeli extends javax.swing.JFrame {

    /**
     * Creates new form AgregarPeli
     */
    public AgregarPeli() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        Clasificacion = new javax.swing.JTextField();
        Duracion = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Categoria = new javax.swing.JTextField();
        Año = new javax.swing.JTextField();
        Descripcion = new javax.swing.JTextField();
        FondoPelsi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(102, 204, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 0, 0));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Agregar Película");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 559, 57));

        jButton2.setBackground(new java.awt.Color(0, 51, 153));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 326, 100, 30));

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 87, 36));

        jLabel1.setBackground(new java.awt.Color(0, 0, 153));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 68, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 153));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Claasificación o Tipo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 122, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 153));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 68, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 153));
        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Categoria:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 122, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 153));
        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Duración:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 190, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 153));
        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 153));
        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Descripcion:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 248, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 153));
        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Año:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 190, -1, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 153));
        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Nombre");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 68, -1, -1));

        Id.setBackground(new java.awt.Color(255, 255, 204));
        Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdActionPerformed(evt);
            }
        });
        Id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IdKeyTyped(evt);
            }
        });
        jPanel1.add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 150, 30));

        Clasificacion.setBackground(new java.awt.Color(255, 255, 204));
        Clasificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClasificacionActionPerformed(evt);
            }
        });
        Clasificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ClasificacionKeyTyped(evt);
            }
        });
        jPanel1.add(Clasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 150, 30));

        Duracion.setBackground(new java.awt.Color(255, 255, 204));
        Duracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DuracionActionPerformed(evt);
            }
        });
        Duracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DuracionKeyTyped(evt);
            }
        });
        jPanel1.add(Duracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 150, 30));

        Nombre.setBackground(new java.awt.Color(255, 255, 204));
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 150, 30));

        Categoria.setBackground(new java.awt.Color(255, 255, 204));
        Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 150, 30));

        Año.setBackground(new java.awt.Color(255, 255, 204));
        Año.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñoActionPerformed(evt);
            }
        });
        Año.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AñoKeyTyped(evt);
            }
        });
        jPanel1.add(Año, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 150, 30));

        Descripcion.setBackground(new java.awt.Color(255, 255, 204));
        Descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescripcionActionPerformed(evt);
            }
        });
        jPanel1.add(Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 150, 30));

        FondoPelsi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/Imagenes/fondo.jpg"))); // NOI18N
        jPanel1.add(FondoPelsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 360));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          new Inicio().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdActionPerformed

    }//GEN-LAST:event_IdActionPerformed

    private void IdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdKeyTyped

        char x = evt.getKeyChar();
        if(x<'0'||x>'9')evt.consume();
    }//GEN-LAST:event_IdKeyTyped

    private void ClasificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClasificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClasificacionActionPerformed

    private void ClasificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ClasificacionKeyTyped

    }//GEN-LAST:event_ClasificacionKeyTyped

    private void DuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DuracionActionPerformed

    private void DuracionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DuracionKeyTyped

        char x = evt.getKeyChar();
        if(x<'0'||x>'9')evt.consume();
    }//GEN-LAST:event_DuracionKeyTyped

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoriaActionPerformed

    private void AñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AñoActionPerformed

    private void AñoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AñoKeyTyped

        char x = evt.getKeyChar();
        if(x<'0'||x>'9')evt.consume();
    }//GEN-LAST:event_AñoKeyTyped

    private void DescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
           
           if(this.Id.getText().isEmpty()|| this.Nombre.getText().isEmpty()||this.Clasificacion.getText().isEmpty()||this.Clasificacion.getText().isEmpty()
                   ||this.Categoria.getText().isEmpty()|| this.Descripcion.getText().isEmpty()||this.Año.getText().isEmpty()||this.Duracion.getText().isEmpty()){
               JOptionPane.showMessageDialog(null,"Debe llenar todos los datos");
           }else{
                 // JOptionPane.showMessageDialog(null,"El ID de la pelucla ya existe");
                 // JOptionPane.showMessageDialog(null,"La pelicula se agrego correctamente");
                    int ID = Integer.parseInt(this.Id.getText());
                    String Nombre = this.Nombre.getText();
                    String Clasificacion = this.Clasificacion.getText();
                    String Categoria = this.Categoria.getText();
                    float Duracion = Float.parseFloat(this.Duracion.getText());
                    int Año = Integer.parseInt(this.Año.getText());
                    String Description = this.Descripcion.getText();
                   if(Clasificacion.equals("a")||Clasificacion.equals("A")){
                       Peliculas PeliA = new Tipo_A ();
                       Peliculas PelinuevaA = new Tipo_A (ID,Nombre,Clasificacion,Categoria,Duracion,Año,Description);
                       PeliA.agregarPeli(PelinuevaA);
                       JOptionPane.showMessageDialog(null,"La Pelicula se agrego correctamente");
                   }else{
                       if(Clasificacion.equals("aa")||Clasificacion.equals("AA")){
                            Peliculas PeliAA = new Tipo_AA ();
                            Peliculas PelinuevaAA = new Tipo_AA (ID,Nombre,Clasificacion,Categoria,Duracion,Año,Description);
                            PeliAA.agregarPeli(PelinuevaAA);
                            JOptionPane.showMessageDialog(null,"La Pelicula se agrego correctamente");
                       }else{
                           if(Clasificacion.equals("b")||Clasificacion.equals("B")){
                                Peliculas PeliB = new Tipo_B ();
                                Peliculas PelinuevaB = new Tipo_B (ID,Nombre,Clasificacion,Categoria,Duracion,Año,Description);
                                PeliB.agregarPeli(PelinuevaB);
                                JOptionPane.showMessageDialog(null,"La Pelicula se agrego correctamente");
                           }else{
                               if(Clasificacion.equals("b15")||Clasificacion.equals("B15")){
                                    Peliculas PeliB15 = new Tipo_B15 ();
                                    Peliculas PelinuevaB15 = new Tipo_B15 (ID,Nombre,Clasificacion,Categoria,Duracion,Año,Description);
                                    PeliB15.agregarPeli(PelinuevaB15);
                                    JOptionPane.showMessageDialog(null,"La Pelicula se agrego correctamente");
                               }else{
                                   if(Clasificacion.equals("c")||Clasificacion.equals("C")){
                                        Peliculas PeliC = new Tipo_C ();
                                        Peliculas PelinuevaC = new Tipo_C (ID,Nombre,Clasificacion,Categoria,Duracion,Año,Description);
                                        PeliC.agregarPeli(PelinuevaC);
                                        JOptionPane.showMessageDialog(null,"La Pelicula se agrego correctamente");
                                   }else{
                                       JOptionPane.showMessageDialog(null,"El tipo de peliculas no esta clasificado"); 
                                   }
                               }
                           }
                       }
                   }
                  
                
           }
        }catch(NumberFormatException nfe){
              JOptionPane.showMessageDialog(null,"El id año o duracion estan mal");
      //} catch (IOException ex) {
            //Logger.getLogger(AgregarPelis.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AgregarPeli.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarPeli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Año;
    private javax.swing.JTextField Categoria;
    private javax.swing.JTextField Clasificacion;
    private javax.swing.JTextField Descripcion;
    private javax.swing.JTextField Duracion;
    private javax.swing.JLabel FondoPelsi;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField Nombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
