/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diseño;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Julio
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VerB = new javax.swing.JButton();
        VerAA = new javax.swing.JButton();
        VerB15 = new javax.swing.JButton();
        VerC = new javax.swing.JButton();
        VerA = new javax.swing.JButton();
        VerTodasPelis = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        AgregarPeli = new javax.swing.JButton();
        VenderPeli = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VerB.setBackground(new java.awt.Color(0, 0, 153));
        VerB.setForeground(new java.awt.Color(204, 255, 255));
        VerB.setText("Ver Peliculas Tipo B");
        VerB.setBorder(null);
        VerB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerBActionPerformed(evt);
            }
        });
        getContentPane().add(VerB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 150, 30));

        VerAA.setBackground(new java.awt.Color(0, 0, 153));
        VerAA.setForeground(new java.awt.Color(204, 255, 255));
        VerAA.setText("Ver Peliculas Tipo AA");
        VerAA.setBorder(null);
        VerAA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerAA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerAAActionPerformed(evt);
            }
        });
        getContentPane().add(VerAA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 150, 30));

        VerB15.setBackground(new java.awt.Color(0, 0, 153));
        VerB15.setForeground(new java.awt.Color(204, 255, 255));
        VerB15.setText("Ver Peliculas Tipo B15");
        VerB15.setBorder(null);
        VerB15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerB15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerB15ActionPerformed(evt);
            }
        });
        getContentPane().add(VerB15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 150, 30));

        VerC.setBackground(new java.awt.Color(0, 0, 153));
        VerC.setForeground(new java.awt.Color(204, 255, 255));
        VerC.setText("Ver Peliculas Tipo C");
        VerC.setBorder(null);
        VerC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerCActionPerformed(evt);
            }
        });
        getContentPane().add(VerC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 150, 30));

        VerA.setBackground(new java.awt.Color(0, 0, 153));
        VerA.setForeground(new java.awt.Color(204, 255, 255));
        VerA.setText("Ver Peliculas Tipo A");
        VerA.setBorder(null);
        VerA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerAActionPerformed(evt);
            }
        });
        getContentPane().add(VerA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 150, 30));

        VerTodasPelis.setBackground(new java.awt.Color(0, 0, 153));
        VerTodasPelis.setForeground(new java.awt.Color(255, 255, 255));
        VerTodasPelis.setText("Todas las Pelis");
        VerTodasPelis.setBorder(null);
        VerTodasPelis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerTodasPelis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerTodasPelisActionPerformed(evt);
            }
        });
        getContentPane().add(VerTodasPelis, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 120, 40));

        Salir.setBackground(new java.awt.Color(102, 153, 255));
        Salir.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 0, 0));
        Salir.setText("Salir");
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, -1, -1));

        AgregarPeli.setBackground(new java.awt.Color(0, 0, 153));
        AgregarPeli.setForeground(new java.awt.Color(204, 255, 255));
        AgregarPeli.setText("Agregar Pelicula");
        AgregarPeli.setBorder(null);
        AgregarPeli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AgregarPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarPeliActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarPeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 120, 40));

        VenderPeli.setBackground(new java.awt.Color(0, 0, 153));
        VenderPeli.setForeground(new java.awt.Color(204, 255, 255));
        VenderPeli.setText("Vender Pelicula");
        VenderPeli.setAutoscrolls(true);
        VenderPeli.setBorder(null);
        VenderPeli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VenderPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VenderPeliActionPerformed(evt);
            }
        });
        getContentPane().add(VenderPeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 120, 40));

        jLabel2.setBackground(new java.awt.Color(0, 0, 255));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mis Peliculas ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 250, 70));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel3.setBackground(new java.awt.Color(0, 0, 153));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Categorias");
        jPanel2.add(jLabel3);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 270));

        jLabel1.setBackground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 390));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, -20, 400, 110));

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 400, 90));
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 70, 80));
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 70, 80));
        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 40, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VerTodasPelisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerTodasPelisActionPerformed
        try {
            // TODO add your handling code here:
            new TodasLasPelis().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
            this.dispose();
    }//GEN-LAST:event_VerTodasPelisActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void AgregarPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarPeliActionPerformed
        // TODO add your handling code here:
        new AgregarPeli().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AgregarPeliActionPerformed

    private void VenderPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenderPeliActionPerformed
        // TODO add your handling code here:
        new VenderPelis().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VenderPeliActionPerformed

    private void VerAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerAActionPerformed
        try {
            new Pelis_TipoA().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_VerAActionPerformed

    private void VerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerBActionPerformed
        try {
            // TODO add your handling code here:
            new Pelis_TipoB().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_VerBActionPerformed

    private void VerAAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerAAActionPerformed
        try {
            new Pelis_TipoAA().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
         this.dispose();
    }//GEN-LAST:event_VerAAActionPerformed

    private void VerB15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerB15ActionPerformed
        try {
            // TODO add your handling code here:
            new Pelis_TipoB15().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
         this.dispose();
    }//GEN-LAST:event_VerB15ActionPerformed

    private void VerCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerCActionPerformed
         try {
            
            new Pelis_TipoC().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
            this.dispose();
    }//GEN-LAST:event_VerCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarPeli;
    private javax.swing.JButton Salir;
    private javax.swing.JButton VenderPeli;
    private javax.swing.JButton VerA;
    private javax.swing.JButton VerAA;
    private javax.swing.JButton VerB;
    private javax.swing.JButton VerB15;
    private javax.swing.JButton VerC;
    private javax.swing.JButton VerTodasPelis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
