/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diseño;

import java.io.IOException;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ptoyecto.Peliculas;
import ptoyecto.Tipo_C;
//import ptoyecto.Tipo_C;

/**
 *
 * @author Julio
 */
public class Pelis_TipoC extends javax.swing.JFrame {

    /**
     * Creates new form Pelis_TipoC
     */
   public Pelis_TipoC() throws IOException {
        initComponents();
           this.setLocationRelativeTo(null);
      /*    Peliculas Pelic = new Tipo_C ();
        ArrayList<String> Pc = new ArrayList(Pelic.MostrarPelis());
        String auc="";
        String au1c="";
        String au12c="";
        System.out.println(Pc.size());   
        for(int i=0;i<Pc.size();i++){
            auc =Pc.get(i);
            StringTokenizer tokc = new StringTokenizer(auc,"/");
            au1c = "Id: "+ tokc.nextToken() +"\n" ;
            au1c += "Nombre: "+ tokc.nextToken()+"\n";
            au1c += "Tipo: "+ tokc.nextToken()+"\n";
            au1c += "Categoria: "+ tokc.nextToken()+"\n";
            au1c += "Duracion: "+ tokc.nextToken()+"\n";
            au1c += "Año: "+ tokc.nextToken()+"\n";
            au1c += "Descripcion: "+ tokc.nextToken()+"\n";
            au12c += au1c +"\n"; 
        }
        this.Text.setText(au12c);
        this.Total.setText("Total: "+ Integer.toString(Pelic.getTotal()));*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BuscarPeli = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Text = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        PeliEncontrada = new javax.swing.JTextArea();
        Buscar = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Total = new java.awt.Label();
        FondoPelsi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BuscarPeli.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(BuscarPeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 260, 30));

        Text.setEditable(false);
        Text.setBackground(new java.awt.Color(255, 255, 204));
        Text.setColumns(20);
        Text.setLineWrap(true);
        Text.setRows(5);
        jScrollPane1.setViewportView(Text);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 260, 230));

        PeliEncontrada.setEditable(false);
        PeliEncontrada.setBackground(new java.awt.Color(255, 255, 204));
        PeliEncontrada.setColumns(20);
        PeliEncontrada.setLineWrap(true);
        PeliEncontrada.setRows(5);
        jScrollPane2.setViewportView(PeliEncontrada);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 170, 230));

        Buscar.setBackground(new java.awt.Color(0, 0, 153));
        Buscar.setText("Buscar");
        Buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BuscarMouseReleased(evt);
            }
        });
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        Regresar.setBackground(new java.awt.Color(0, 0, 153));
        Regresar.setText("Regresar");
        Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Total.setAlignment(java.awt.Label.CENTER);
        Total.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jPanel1.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 150, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 70));

        FondoPelsi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(FondoPelsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarMouseReleased

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
     /*   Peliculas Pelis = new Tipo_C ();
        if(this.BuscarPeli.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"No se ingreso nada");
        }else{
            try {
                boolean val = false;
                
                String Nombre= this.BuscarPeli.getText();
                String Nombre1 = Nombre.toLowerCase();
                Peliculas PeliA = new Tipo_C();
                String Au = "";
                String Au1 = "";
                String Au11 = "";
                String XX = "";
                String XX2 = "";
                ArrayList<String> Arr = new ArrayList(PeliA.MostrarPelis());
                for(int i=0;i<Arr.size();i++){
                    Au = Arr.get(i);
                    StringTokenizer to = new StringTokenizer(Au,"/");
                    to.nextToken();
                    Au1 = to.nextToken();
                    Au11 = Au1.toLowerCase();
                    if(Au11.equals(Nombre)||Au11.equals(Nombre1)){
                        XX = Arr.get(i);
                        StringTokenizer tok = new StringTokenizer (XX,"/");
                        XX = "Id: "+ tok.nextToken() +"\n" ;
                        XX+= "Nombre: "+ tok.nextToken()+"\n";
                        XX += "Tipo: "+ tok.nextToken()+"\n";
                        XX += "Categoria: "+ tok.nextToken()+"\n";
                        XX += "Duracion: "+ tok.nextToken()+"\n";
                        XX += "Año: "+ tok.nextToken()+"\n";
                        XX += "Descripcion: "+ tok.nextToken()+"\n";
                        XX2 += XX +"\n"; 
                        this.PeliEncontrada.setText(XX2);
                        val = true;
                    }
                }
                if(val!=true){
                    JOptionPane.showMessageDialog(null,"No Tienes peliculas de esta clasificación con ese nombre");
                }
            } catch (IOException ex) {
                Logger.getLogger(Pelis_TipoA.class.getName()).log(Level.SEVERE, null, ex);
            }
            
           
        }*/

    }//GEN-LAST:event_BuscarActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
        new Inicio().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pelis_TipoC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pelis_TipoC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pelis_TipoC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pelis_TipoC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Pelis_TipoC().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Pelis_TipoC.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JTextField BuscarPeli;
    private javax.swing.JLabel FondoPelsi;
    private javax.swing.JTextArea PeliEncontrada;
    private javax.swing.JButton Regresar;
    private javax.swing.JTextArea Text;
    private java.awt.Label Total;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
