/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diseño;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ptoyecto.Peliculas;

/**
 *
 * @author Julio
 */
public class VenderPelis extends javax.swing.JFrame {

    /**
     * Creates new form VenderPelis
     */
    public VenderPelis() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        vender = new javax.swing.JButton();
        Idvender = new javax.swing.JTextField();
        Titulo1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Ver = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 153));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Regristrar pelicula");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 250, 50));

        Regresar.setBackground(new java.awt.Color(0, 0, 153));
        Regresar.setText("Regresar");
        Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 100, 30));

        buscar.setBackground(new java.awt.Color(0, 0, 153));
        buscar.setText("Buscar");
        buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 90, 20));

        vender.setBackground(new java.awt.Color(0, 0, 153));
        vender.setText("Vender");
        vender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venderActionPerformed(evt);
            }
        });
        getContentPane().add(vender, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 100, 30));

        Idvender.setBackground(new java.awt.Color(255, 255, 204));
        Idvender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdvenderActionPerformed(evt);
            }
        });
        Idvender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IdvenderKeyTyped(evt);
            }
        });
        getContentPane().add(Idvender, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 220, 30));

        Titulo1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(0, 0, 153));
        Titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo1.setText("ID:");
        getContentPane().add(Titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 100, 20));

        Ver.setEditable(false);
        Ver.setBackground(new java.awt.Color(255, 255, 204));
        Ver.setColumns(20);
        Ver.setLineWrap(true);
        Ver.setRows(5);
        jScrollPane2.setViewportView(Ver);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 220, 150));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 70));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 240, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño/Imagenes/fondo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 540, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
        new Inicio().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegresarActionPerformed

    private void venderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venderActionPerformed
        int id = Integer.parseInt(this.Idvender.getText());
        int opcion = JOptionPane.showConfirmDialog(null,"Desea vende esta pelicula");
       /* if(JOptionPane.YES_OPTION == opcion){
            Peliculas Peli = new Peliculas();
            try {
                Peli.venderPeli(id);
            } catch (IOException ex) {
                Logger.getLogger(VenderPelis.class.getName()).log(Level.SEVERE, null, ex);
            }
               JOptionPane.showMessageDialog(null,"Listo");
        }*/
        if(JOptionPane.NO_OPTION == opcion){
               JOptionPane.showMessageDialog(null,"No realizo la venta");
        }
        if(JOptionPane.CANCEL_OPTION == opcion){
               JOptionPane.showMessageDialog(null,"Cancelo la venta");
        }
    }//GEN-LAST:event_venderActionPerformed

    private void IdvenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdvenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdvenderActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
      /*  Peliculas VenderPeli =  new Peliculas();
        int id = Integer.parseInt(this.Idvender.getText());
        String ob ="";
        try {
            for(Peliculas apun:VenderPeli.CrearObjects()){
                if(id == apun.getID()){
                    ob = apun.toString();
                }
                
            }
        } catch (IOException ex) {
            Logger.getLogger(VenderPelis.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.Ver.setText(ob);
        */
    }//GEN-LAST:event_buscarActionPerformed

    private void IdvenderKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdvenderKeyTyped

          char x = evt.getKeyChar();
        if(x<'0'||x>'9')evt.consume();
    }//GEN-LAST:event_IdvenderKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VenderPelis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VenderPelis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VenderPelis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VenderPelis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VenderPelis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Idvender;
    private javax.swing.JButton Regresar;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JTextArea Ver;
    private javax.swing.JButton buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton vender;
    // End of variables declaration//GEN-END:variables
}
